---
- name: Converge
  hosts: all
  tasks:
    - name: Include main role
      ansible.builtin.import_role:
        name: ea31337.mt_runner
      vars:
        mt_runner_bt_mt5_config:
          Common:
            Login: "{{ ansible_facts.env.MT_RUNNER_MT5_LOGIN }}"
            Password: "{{ ansible_facts.env.MT_RUNNER_MT5_PASSWORD }}"
            Server: MetaQuotes-Demo
          Tester:
            Deposit: 10000
            ExecutionMode: 0
            Expert: EA31337-Elite-v3.000-rc1.ex5
            FromDate: 2024.01.01
            Leverage: 1:500
            Login: "{{ ansible_facts.env.MT_RUNNER_MT5_LOGIN }}"
            Model: 1
            Period: M15
            Report: report.html
            ReplaceReport: 1
            ShutdownTerminal: 1
            Symbol: EURUSD
            ToDate: 2024.01.11
        mt_runner_get_url_list:
          - dest: "{{ mt_runner_mt_path }}/MQL5/Experts"
            url: https://github.com/EA31337/EA31337/releases/download/v3.000-rc1/EA31337-Elite-v3.000-rc1.ex5
