---
driver:
  name: docker
lint: |
  set -e
  #  yamllint .
  #  ansible-lint
platforms:
  - name: ubuntu-latest
    image: ubuntu:latest
provisioner:
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-tmp-$${USER}
  env:
    MT_RUNNER_MT5_LOGIN: "${MT_RUNNER_MT5_LOGIN}"
    MT_RUNNER_MT5_PASSWORD: "${MT_RUNNER_MT5_PASSWORD}"
  name: ansible
  inventory:
    group_vars:
      all:
        wine_install_winetricks: true
verifier:
  name: ansible
