---
- name: Converge
  hosts: all
  tasks:
    - name: Include main role
      ansible.builtin.import_role:
        name: ea31337.mt_runner
      vars:
        mt_runner_bt_mt5_config:
          Tester:
            Expert: Advisors/ExpertMACD
