---
driver:
  name: docker
lint: |
  set -e
  #  yamllint .
  #  ansible-lint
platforms:
  - env:
      MT_RUNNER_MT5_LOGIN: "${MT_RUNNER_MT5_LOGIN:-12345}"
      MT_RUNNER_MT5_PASSWORD: "${MT_RUNNER_MT5_PASSWORD:-SETME}"
    groups:
      - mt5
    image: ubuntu:latest
    name: ubuntu-latest
provisioner:
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-tmp-$${USER}
  name: ansible
  inventory:
    group_vars:
      all:
        wine_install_winetricks: true
verifier:
  name: ansible
