---
- name: Converge
  hosts: all
  tasks:
    - name: Include main role
      include_role:
        name: ansible-role-mt-runner
      vars:
        metatrader_setup_url: |
          https://download.mql5.com/cdn/web/3315/mt4/xm4setup.exe
        metatrader_version: 4
