---
- name: Converge
  hosts: all
  tasks:
    - name: Include main role
      ansible.builtin.include_role:
        name: ea31337.mt_runner
      vars:
        # noqa: var-naming[no-role-prefix]
        metatrader_setup_url: |
          https://download.mql5.com/cdn/web/3315/mt4/xm4setup.exe
        metatrader_version: 4
