---
driver:
  name: docker
lint: |
  set -e
  #  yamllint .
  #  ansible-lint
platforms:
  - env:
      MT_RUNNER_MT4_LOGIN: "${MT_RUNNER_MT4_LOGIN:-12345}"
      MT_RUNNER_MT4_PASSWORD: "${MT_RUNNER_MT4_PASSWORD:-SETME}"
    groups:
      - mt4
    image: ubuntu:jammy
    name: ubuntu-jammy
provisioner:
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-tmp-$${USER}
  name: ansible
  inventory:
    group_vars:
      all:
        wine_install_winetricks: true
verifier:
  name: ansible
